---
title: "Linear Regression Mini-competition"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(caTools)
```

```{r}
# Load the data
news_data <- read.csv("~/R/STA_631/mini_competition01/news.csv")
```

```{r}
#split the dataset
set.seed(143)

#Use 70% of dataset as training set and remaining 30% as testing set
sample <- sample.split(news_data$SentimentHeadline, SplitRatio = 0.7)
train  <- subset(news_data, sample == TRUE)
test   <- subset(news_data, sample == FALSE)

```

```{r}
# write the train set
write_csv(train, "train_set.csv")
```

Exploratory analysis
```{r}
skimr::skim(news_data)
```

1. Convert the PublishDate to just month and date 
2. Clean the social media popularity scores, set the negatives to 0s.
3. Combine the social media scores into one variable.
4. Look into correlation between Sentiment Headline and Sentiment title.

```{r}
# Convert PublishDate to POSIXct object
datetime <- as.POSIXct(train$PublishDate, format = "%m/%d/%Y %H:%M")

# Split into date and time
train$date_part <- as.Date(datetime)
train$time_part <- format(datetime, "%H:%M")

```

```{r}
train$Facebook <- ifelse(train$Facebook < 0, 0, train$Facebook)
train$GooglePlus <- ifelse(train$GooglePlus < 0, 0, train$GooglePlus)
train$LinkedIn <- ifelse(train$LinkedIn < 0, 0, train$LinkedIn)

```

```{r}
train$social_media <- train$Facebook + train$GooglePlus + train$LinkedIn
```

```{r}
clean_train <- train %>% 
  select(Title, Headline, Topic, SentimentTitle, SentimentHeadline, date_part, time_part, social_media)
```

```{r}
clean_train$Topic <- as.factor(clean_train$Topic)
```

```{r}
# hist plots
clean_train %>%
  ggplot(aes(x = SentimentHeadline, color = Topic)) +
  geom_freqpoly() +
  labs(x = "Sentiment Headline", y = "Frequency") +
  theme_minimal()
```
```{r}
clean_train %>%
  ggplot(aes(x = SentimentHeadline)) +
  geom_histogram(binwidth = 0.1, fill = "skyblue", color = "black") +
  labs(x = "Sentiment Headline", y = "Frequency") +
  theme_minimal()
```
```{r}
clean_train %>%
  ggplot(aes(x = social_media)) +
  geom_histogram(binwidth = 0.1, fill = "skyblue", color = "black") +
  labs(x = "Social Media Popularity", y = "Frequency") +
  theme_minimal()
```



```{r}
# Fit the ANOVA model
anova_model <- aov(SentimentHeadline ~ Topic, data = clean_train)

# Summary of the ANOVA model
summary(anova_model)
```

```{r}
# Create a violin plot
ggplot(clean_train, aes(x = Topic, y = SentimentHeadline)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, fill = "dodgerblue", color = "black", outlier.shape = NA) +  # Add boxplot without outliers
  labs(x = "Topic", y = "Sentiment Headline Score") +
  theme_minimal()

```

```{r}
# Calculate the correlation coefficient
correlation_coefficient <- cor(clean_train$SentimentHeadline, clean_train$SentimentTitle)
correlation_test <- cor.test(clean_train$SentimentHeadline, clean_train$SentimentTitle)
print(correlation_test)
```
```{r}
# Calculate the correlation coefficient
correlation_coefficient <- cor(clean_train$SentimentHeadline, clean_train$social_media)
correlation_test <- cor.test(clean_train$SentimentHeadline, clean_train$social_media)
print(correlation_test)
```
```{r}
model <- lm(SentimentHeadline ~ SentimentTitle + social_media + num_Topic, data = clean_train)
summary(model)

```


